apiVersion: batch/v1
kind: Job
metadata:
  name: stage-input-data
spec:
  template:
    spec:
      containers:
      - name: stage-input-data
        # Jobs cannot use ImageStream images directly, so we have to provide the registry/repo variant
        image: 172.30.1.1:5000/calrissian/calrissian:latest
        command:
        - "sh"
        - "-c"
        - "cp input-data/* /calrissian/input-data/"
        volumeMounts:
        - mountPath: /calrissian/input-data
          name: calrissian-input-data
      restartPolicy: OnFailure
      volumes:
      - name: calrissian-input-data
        persistentVolumeClaim:
          claimName: calrissian-input-data
